config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  get 'reports/index', :to => 'reports#index', :as => 'reports'
  get '/month_report/', :to => 'month_reports#show', :as => 'month_report'
  get '/month_report/export', :to => 'month_reports#export', :as => 'export'
  get '/formulas/show/:formula', :to => 'formulas#show', :as => 'formula'

  # Api v1
  namespace :api do
    namespace :v1 do
     resources :currencies do 
      resources :manuals, only: %i[index create destroy]
     end
    end
  end

  resources :currencies
  resources :transaction_types
  resources :creditors
  
  resources :debts do
    resources :attachments
      collection do
        get 'search'
      end
    resources :transaction_items, :except => :show
  end
  
 
  root 'debts#index'
end

app/models/transaction_item.rb
# frozen_string_literal: true

class TransactionItem < ApplicationRecord
  
  belongs_to :transaction_info
  has_one :debt, :through => :transaction_info

  before_save :set_start_balance, :if => :blank_start_balance?

  validates :transaction_info_id, :presence => true
 
  validates :value, :presence => true
  
  def editable?
    true
  end

  def final_outstanding_balance
    Dentaku.enable_ast_cache!
    result = start_balance
    result = Dentaku("#{start_balance} #{transaction_info.category.operation} #{value}") if amortization? || withdraw?
    
    result
  end

  def period
    result = Arel.sql(transaction_info.payment_date - date).to_i
    result = 30 if result == 31
    result
  end

  def future_transaction?
    if new_record? || (withdraw? && !confirmed?)
      true
    else
      false
    end		
  end

  def withdraw?
    transaction_info.category_number == 1
  end

  def amortization?
    transaction_info.category_number == 2
  end

  def interest?
    transaction_info.category_number == 3
  end

  def charge?
    transaction_info.category_number == 4
  end

  private

  def set_start_balance
    self.start_balance = debt.outstanding_balance
  end

  def blank_start_balance?
    start_balance.blank?
  end
end

app/controllers/transaction_items_controller.rb
# frozen_string_literal: true

class TransactionItemsController < ApplicationController  
  before_action :set_transaction, :only => [:edit, :update, :destroy]
  before_action :set_debt, :only => [:index, :new, :edit, :create, :update]
  before_action :set_start_date, :only => [:index, :create, :update]
  before_action :set_transaction_set, :only => [:index]  

  # GET :debt_id/transactions/
  def index    
    render :index, :layout => false
  end

  # GET :debt_id/transaction/new
  def new  	
    @transaction_item = TransactionItem.new()
    @transaction_item.debt = @debt
    render :new, :layout => false
  end

  # GET :debt_id/transactions/1/edit
  def edit
    render :edit, :layout => false
  end

  # POST :debt_id/transactions
  def create
    @transaction_item = TransactionItem.new(transaction_item_params)
    
    if @transaction_item.save
      set_transaction_set
      render :_index, :layout => false, :notice => 'O registro foi salvo com sucesso.'        
    else
      render :new, :layout => false, :status => :unprocessable_entity
    end
  end

  # PATCH/PUT :debt_id/transactions/1
  def update
    if @transaction_item.update(transaction_item_params)
      set_transaction_set
      render :_index, :layout => false, :notice => 'O registro foi salvo com sucesso.'        
    else
      render :edit, :layout => false, :status => :unprocessable_entity        
    end
  end

  # DELETE :debt_id/transactions/1
  # DELETE :debt_id/transactions/1.json
  def destroy
    @transaction_item.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, :notice => 'O registro foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
        @debt = Debt.find(params[:debt_id])
         
    end

    def set_transaction
      @transaction_item = TransactionItem.find(params[:id])
      
    end

    def set_transaction_set       
      @transaction_set =  TransactionSet.new(@debt, @start_date)

    end

    def set_start_date      
      @start_date = @debt.projection_start_date
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_item_params
      params.require(:transaction_item).permit(:value, 
                                          :value_brl, 
                                          :exchange_rate,
                                          :date, 
                                          :debt_id,
                                          :transaction_info_id,  
                                          :id,
                                          :internalization_date,
                                          :formula,
                                          :confirmed)
    end
end

app/views/transaction_items/_form.html.erb
<%= simple_form_for transaction_item, url: new_debt_transaction_item_path(debt), as: :transaction_item do |f| %>
  <div class="modal-body">
    
    <%= f.input :transaction_info_id, label: 'Tipo', collection: debt.transaction_infos, label_method: :category_name, value_method: :id, disabled: f.object.persisted? %>
    
    <%= f.input :value_brl, as: :string, placeholder: "Digite o valor", input_html: {value: big_decimal_to_currency(f.object.value_brl, 2) || '', class: 'currency-brl mask-field'} %> 
   
    <%= f.input :exchange_rate, placeholder: "Digite o valor",  as: :string, input_html: {class: 'currency_exchange_rate'}%>
   
    <div class="row transaction-formula">
      <div class="col-6">
        <%= f.input :value, placeholder: "Digite o valor", as: :string,
         input_html: {value: big_decimal_to_currency(f.object.value, 6), class: 'currency mask-field'} %>
      </div>
      <div class="col-6">
        <%= f.input :formula %>
      </div>
    </div>
    <div class="row">
    <div class="col-6">
     <%= f.label :date %>
     
     <%= f.text_field :date, as: :date, class: "form-control string date_flatpickr" %>
    </div>
    <div class="col-6">
    <%= f.label :internalization_date, include_blank: true if debt.externo? %>
    <%= f.text_field :internalization_date, as: :date, class: "form-control string date_flatpickr", include_blank: true if debt.externo? %>  
    </div>
    </div>
   
     
    
  </div>
<% end %>

<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>

  <% if transaction_item.new_record? %>
    <% http_verb = 'post' %>
    <% path = debt_transaction_items_path(@debt) %>
  <% else %>
    <% http_verb = 'patch' %>
    <% path = debt_transaction_item_path(@debt, transaction_item) %>
  <% end %>

  <button type="button" class="btn btn-success transaction-save" data-http-verb="<%= http_verb %>" data-path='<%= path %>'>Salvar</button>
</div>
 
<%= javascript_pack_tag 'libs/transaction'  %>

app/views/transaction_items/_index.html.erb
 
<div class='nav transactions-year-list position-fixed'>
	<ul class=" list-group">
		<% @debt.years_list.each do |year| %> 
			<li class="nav-item">
				<a class="nav-link list-group-item list-group-item-action year-link <%= 'active' if year == Date.today.year %>" href="#<%= year %>"><%= year %></a>
			</li>
		<% end %>
	</ul>
</div>

<div class='pull-left debt-ops'>
	
	<table id="datatable" class="table table-hover">
	
		<thead>
			<tr class="table-primary">
				 <th></th>
				<th class="td-right">Data</th>
				<th class="td-right val_moeda">Valor em moeda </th>
				<th class="td-right val_brl">Valor em moeda (BRL)</th>
				<th class="td-right">Operação</th>
				
				 
			</tr>
		</thead>
		
		<tbody>

			 
			<%  @transaction_set.items.each_with_index do |transaction_item, index| %>
			<% transaction_item.editable? ? transaction_class = 'edit-transaction' : transaction_class = 'block-edit-transaction' %>
			<% transaction_edit_path = edit_debt_transaction_item_path(@debt, transaction_item) if transaction_item.editable? %>
			<% date_transaction = transaction_item.date.to_s < Date.today.to_s %>
			<% transaction_class = transaction_class + 'table-danger' if transaction_item.withdraw? and 
			    date_transaction and !transaction_item.confirmed? %>
			
			<tr id="ti_<%= transaction_item.id %>" class="<%= transaction_class %>" data-path='<%= transaction_edit_path %>'>
					 
					
					<td class="td-right">
						<% if transaction_item.future_transaction? %>
							<span class="badge badge-secondary badge-pill"><%= transaction_item.transaction_info.slug %></span>
						<% elsif transaction_item.withdraw? %>
							<span class="badge badge-primary badge-pill"><%= transaction_item.transaction_info.slug %></span>
						<% elsif transaction_item.amortization?  %>
							<span class="badge badge-warning badge-pill"><%= transaction_item.transaction_info.slug %></span>
						<% elsif transaction_item.interest?  %>
							<span class="badge badge-success badge-pill"><%= transaction_item.transaction_info.slug %></span>
						<% elsif transaction_item.charge?  %>
							<span class="badge badge-info badge-pill"><%= transaction_item.transaction_info.slug %></span>            
						<% end %>
					</td>
					<td class="td-right">
					<a id="<%= transaction_item.date.try(:strftime, "%Y")%>"></a>
						<%= transaction_item.date.try(:strftime, "%d/%m/%Y") %>
					</td>
				
					<td class="td-right val_moeda">
					 <%= big_decimal_to_currency(transaction_item.value, @debt.decimal_places) || '-'  %>                 
					</td>

					<td class="td-right val_brl">
					 <%= big_decimal_to_currency(transaction_item.value_brl, @debt.decimal_places) || '-'  %>                 
					</td>

					<td class="td-right">            
						<%= transaction_item.transaction_info.category.name %>
					</td>     
						 
				</tr>

				<% if (@transaction_set.items[index + 1].present? && transaction_item.date.month != @transaction_set.items[index + 1].date.month)  || @transaction_set.items.count == index - 1 %>
				 
					<% (0..( @transaction_set.items[index + 1].date.year * 12 + @transaction_set.items[index + 1].date.month) - (transaction_item.date.year * 12 + transaction_item.date.month) - 1 ).each do |month| %>
						<tr class="table-info">
							<td class="td-right" colspan="2"><strong>Saldo em: <%= (transaction_item.date + month.month).end_of_month.try(:strftime, "%d/%m/%Y") %>:</strong></td>
							<td class="td-right"><strong><%= big_decimal_to_currency((@transaction_set.balance_by transaction_item.date), @debt.decimal_places) %></strong></td>
							 
							<td></td>

						 
							 
						</tr>
					<% end %>
					
				<% end %>
			<%  end %>  
				
		</tbody>
			<thead>
			<tr class="table-primary">
				 
				<th class="td-right">Data</th>
				<th class="td-right val_moeda">Valor em moeda </th>
				<th class="td-right val_brl">Valor em moeda (BRL)</th>
				<th class="td-right">Operação</th>
				 <th></th>
				  
			</tr>
		</thead>
	</table>
		
	<br>
		 
</div>

<div class="pull-left transactions-legend">
	<div class='position-fixed'>
		<!-- <button type="button" class="btn btn-primary btn-converte">Converter Moeda</button>
		<br><br> -->
		<ul class="nav flex-column list-group">     
			<li><span class="badge badge-primary badge-pill"><%= @debt.transaction_infos.find_by(category_number: 1).slug %></span> Desembolso</li>           
			<li><span class="badge badge-warning badge-pill"><%= @debt.transaction_infos.find_by(category_number: 2).slug %></span> Amortização</li>
			<li><span class="badge badge-success badge-pill"><%= @debt.transaction_infos.find_by(category_number: 3).slug %></span> Juros</li>

			<% @debt.transaction_infos.where(category_number: 4).order(:slug).each do |transaction_info| %>
				<li><span class="badge badge-info badge-pill"><%= transaction_info.slug %></span> <%= transaction_info.description %></li>
			<% end %>
			<li>&nbsp</li>
			<li>Operações futuras:</li>
			<li><span class="badge badge-secondary badge-pill"><%= @debt.transaction_infos.find_by(category_number: 1).slug %></span> Desembolso</li>           
			<li><span class="badge badge-secondary badge-pill"><%= @debt.transaction_infos.find_by(category_number: 2).slug %></span> Amortização</li>
			<li><span class="badge badge-secondary badge-pill"><%= @debt.transaction_infos.find_by(category_number: 3).slug %></span> Juros</li>
			<% @debt.transaction_infos.where(category_number: 4).order(:slug).each do |transaction_info| %>
				<li><span class="badge badge-secondary badge-pill"><%= transaction_info.slug %></span> <%= transaction_info.description %></li>
			<% end %>              
			<span hidden class="currency-name"><%= @debt.currency.try(:name) %></span>      
		</ul>
		<br>
		<button type="button" class="btn btn-success new-withdraw" data-toggle="modal" data-target="#transactionModal" data-path="<%= new_debt_transaction_item_path(@debt) %>">Registrar movimentação</button>
	</div>  
</div>
<%= javascript_pack_tag('libs/ancora') %>
<script type="text/javascript">
	 
	initTransactionActions();

	$('.val_brl').hide();
	// $('.btn-converte').text('Converter para BRL');

	// if ($('.currency-name').text() == 'BRL'){
	//    $('.btn-converte').attr("disabled", true);
	// }else{
	//    $('.btn-converte').attr("disabled", false);
	// }

	// $('.btn-converte').on('click', function(e){
	//   if( $('.val_moeda').is( ":hidden" ) ) {
	//     $('.val_moeda').show();
	//     $('.val_brl').hide();
	//     $('.btn-converte').text('Converter para BRL');
	//   } else if($('.val_brl').is( ":hidden" )){
	//     $('.val_brl').show();
	//     $('.val_moeda').hide();
	//     $('.btn-converte').text('Converter para ' + '<%= @debt.currency.try(:name) %>');
	//   }
	// })
</script>

app/views/transaction_items/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Editar <%= @transaction_item.transaction_info.category.name.downcase %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', debt: @debt, transaction_item: @transaction_item %>

app/views/transaction_items/new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Registrar movimentação</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', debt: @debt, transaction_item: @transaction_item %>
 