config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  get 'reports/index', :to => 'reports#index', :as => 'reports'
  get '/month_report/', :to => 'month_reports#show', :as => 'month_report'
  get '/month_report/export', :to => 'month_reports#export', :as => 'export'
  get '/formulas/show/:formula', :to => 'formulas#show', :as => 'formula'

  # Api v1
  namespace :api do
    namespace :v1 do
     resources :currencies do 
      resources :manuals, only: %i[index create destroy]
     end
    end
  end

  resources :currencies
  resources :transaction_types
  resources :creditors
  
  resources :debts do
    resources :attachments
      collection do
        get 'search'
      end
    resources :transaction_items, :except => :show
  end
  
 
  root 'debts#index'
end

app/models/debt.rb
# frozen_string_literal: true

class Debt < ApplicationRecord
  belongs_to :creditor
  belongs_to :financial_agent, :class_name => 'Creditor', :optional => true
  belongs_to :currency

  has_many :attachments
  has_many :transaction_infos
  has_many :transaction_items, :through => :transaction_infos, :source => :items
  
  accepts_nested_attributes_for :transaction_infos, :allow_destroy => true
 
  enum :category => { :interno => 0, :externo => 1 }
  enum :amortization_type => { :sac => 0, :price => 1, :single => 2 }
  enum :legislation_level => { :federal => 0, :estadual => 1, :municipal => 2 }
  
  validates :code, :presence => true, :numericality => { :only_integer => true }, :length => { :is => 6 }
  validates :contract_value, :presence => true
  validates :signature_date, :presence => true
  validates :amortization_period, :presence => true
  validates :currency, :presence => true
  validates :loan_term, :presence => true
  validates :decimal_places, :presence => true
  validate  :valid_dates?
 
  scope :code_query, -> (code_query) {where code: code_query}
  scope :name_query, -> (name_query) {where("name ilike ?", "#{name_query}%")}
  scope :signature_year_query, -> (signature_year_query) {
             where signature_date: date_range_from_year(signature_year_query.to_i)}
  scope :creditor_query, -> (creditor_query) {where creditor_id: creditor_query}
  #scope :status_query, -> (status_query) {select(Debt.status == status_query)}

  
  def init
    TransactionInfo::BASIC_TYPES.keys.each do |category_number|
      transaction_infos << TransactionInfo.new( :category_number => category_number )
     end
  end
  
  # Desembolsos
  def withdraws
    transaction_items.where(:transaction_infos => { :category_number => 1 })
  end

  # Amortizações
  def amortizations
    transaction_items.where(:transaction_infos => { :category_number => 2 })
  end 
    
  # Juros
  def interests
    transaction_items.where(:transaction_infos => { :category_number => 3 })
  end

  def charges_grace_period
    date_withdraw = transaction_items.where(:transaction_infos => { :category_number => 1 }).order('date').first.date

    (grace_period.year * 12 + grace_period.month) - (date_withdraw.year * 12 + date_withdraw.month)
  end

  # Próxima parcela
  def next_instalment
    outstanding_balance * instalment_formula_numerator / instalment_formula_denominator
  end	
    
  ['next_instalment', 'amortization', 'interest', 'outstanding_balance'].each do |method_name|
    define_method :"show_#{method_name}" do 
      Decimal.new(self.send(method_name).to_f)
    end
  end

  # Juros
  def interest(interest_rate = self.interest_rate)
    withdraws_total = 0
    withdraws.where(:date => reference_period).find_each do |withdraw|
    withdraws_total += withdraw.value * interest_rate / 360 * (payment_date - (withdraw.date - 1.day)).to_i
    end

    (30 * outstanding_balance * interest_rate / 360 ) - withdraws_total
  end

  def contract_value_brl
    contract_value / currency.to_brl	
  end

  def status
    if in_grace_period?
      return 'Carência'
    elsif in_amortization_period?
      return 'Amortização'
    elsif finished?
      return 'Finalizada'
    end
  end

  def new_debt?
    transaction_items.count == 0
  end

  def in_grace_period?
    grace_period > Date.today && !finished?
  end

  def in_amortization_period?
    grace_period < Date.today && !finished?
  end

  def finished?
    #balance == 0
    false
  end

  def balance
     instalment_sum == amortizations.sum(:value_cents)
  end

  # Saldo devedor
  def outstanding_balance(final_date = Date.today - 1)
    withdraws.where(:date => signature_date..final_date, :confirmed => true).sum(:value) - amortizations.where(:date => signature_date..final_date).sum(:value)
  end

  def years_list
    signature_date.year..(grace_period + loan_term.months).year
  end

  def withdraws_pro_rata
    result = []
    withdraws.where(:date => reference_period).find_each do |withdraw|
      result += result + [withdraw.value * withdraw.period]
    end
  end

  def withdraws_values_by_year(end_date)		
    withdraws.where('date <= ?', end_date).order(Arel.sql('extract(year from date)')).group('extract(year from date)').pluck(Arel.sql('extract(year from date), sum(value), sum(value_brl)'))
  end

  def transaction_items_month_total(date, category_number = nil)	
    result = transaction_items.where('extract(month from date) = ?', date.month).where('extract(year from date) = ?', date.year)
    result = result.where(:transaction_infos => { :category_number => category_number }) if category_number.present? && category_number != 1
    result = result.sum(:value_brl)
  end

  def transaction_items_year_total(date, category_number = nil)		
    result = transaction_items.where(:date => date.beginning_of_year..date.end_of_month)
    result = result.where(:transaction_infos => { :category_number => category_number }) if category_number.present? && category_number != 1
    result = result.reject(&:withdraw?).sum(&:value_brl)
  end

  def last_year
    (grace_period + loan_term.months).year
  end

  def last_exchange_rate(end_date)		
    transaction_items.where('date < ?', end_date).reject(&:withdraw?).sort_by(&:date).last.try(:exchange_rate)
  end

  delegate :count, :to => :amortizations, :prefix => true

  def grace_period_payments_number
    (grace_period.year * 12 + grace_period.month) - (signature_date.year * 12 + signature_date.month)
  end

  def until_first_payment_in_months		
    interests.first.present? ? final_date = interests.first.date : final_date = grace_period
    (final_date.year * 12 + final_date.month) - (signature_date.year * 12 + signature_date.month)
  end

  def paid_payments_count(payment_type, end_date)
    send(payment_type).where('date <= ?', end_date).count
  end

  def projection_start_date
    if amortizations.present?
      frequency = transaction_infos.find_by(:category_number => 2).frequency
      amortizations.last.date + TransactionInfo.frequencies[frequency].months
    elsif interests.present?	
      frequency = transaction_infos.find_by(:category_number => 3).frequency			
      interests.last.date + TransactionInfo.frequencies[frequency].months		
    # elsif done?
    # 	false
    else
      signature_date
    end
  end

  def paid_in?
    withdraws.sum(:value) >= contract_value
  end

  private

    def self.date_range_from_year(year)
      Date.new(year)..(Date.new(year + 1) - 1.day)
    end

    def instalment_formula_numerator
      ( ( (1 + interest_rate_per_month) ** (loan_term - amortizations_count) ) * interest_rate_per_month )
    end

    def instalment_formula_denominator
      ( ( ( 1 + interest_rate_per_month ) ** (loan_term - amortizations_count) ) - 1 )
    end

    def interest_rate_per_month
      interest_rate
    end

    def valid_dates?
      if signature_date > grace_period				
        errors.add(:signature_date, 'deve ser anterior ao prazo de carência')
        errors.add(:grace_period, 'deve ser posterior à data de assinatura')
      elsif grace_period > amortization_period				
        errors.add(:grace_period, 'deve ser anterior ao prazo de amortização')
        errors.add(:amortization_period, 'deve ser posterior ao prazo de carência')
      end
    end
end

app/controllers/debts_controller.rb
# frozen_string_literal: true

class DebtsController < ApplicationController
  before_action :set_debt, :only => [:show, :edit, :update, :destroy]
  before_action :set_start_date, :only => [:show]
 
  # GET /debts
  # GET /debts.json
  def index
     @pagy, @debts = pagy(Debt.all)
  end

  def search 
    @debts = Debt.where(nil)
    @debts = Debt.code_query(params[:code_query]) if params[:code_query].present?
    @debts = Debt.name_query(params[:name_query]) if params[:name_query].present?
    #@debts = Debt.status_query(params[:status_query]) if params[:status_query].present?
    @debts = Debt.creditor_query(params[:creditor_query]) if params[:creditor_query].present?
    @debts = Debt.signature_year_query(params[:signature_year_query]) if params[:signature_year_query].present?
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
   
    @attachments = Attachment.all.where(:debt_id => @debt.id)
  end

  # GET /debts/new
  def new
    @debt = Debt.new
    @debt.init
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts
  # POST /debts.json
  def create    
    @debt = Debt.new(debt_params)

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, :notice => I18n.t(:save_success) }
        format.json { render :show, :status => :created, :location => @debt }
      else
        format.html { render :new }
        format.json { render :json => @debt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1
  # PATCH/PUT /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to @debt, :notice => I18n.t(:save_success) }
        format.json { render :show, :status => :ok, :location => @debt }
      else
        format.html { render :edit }
        format.json { render :json => @debt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt.destroy
    respond_to do |format|
      format.html { redirect_to debts_url, :notice => 'Debt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    def set_start_date
      @transaction_item = TransactionItem.find(params[:id]) 
      @start_date = @debt.projection_start_date
      @transaction_set =  TransactionSet.new(@debt, @start_date)     
    end

 

 
    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:code, 
                                   :contract_value,                                   
                                   :signature_date, 
                                   :creditor_id,
                                   :grace_period,                                   
                                   :amortization_period, 
                                   :purpose,
                                   :amortization_type,                                   
                                   :financial_agent_id,
                                   :applicable_legislation,
                                   :legislation_level,
                                   :name,
                                   :category,
                                   :currency_id,
                                   :notes,                                   
                                   :loan_term,
                                   :interest_rate,
                                   :decimal_places,
                                   :start_amt_next_month_to_grace_period,
                                   :transaction_infos_attributes => [:id,
                                                                     :_destroy,
                                                                     :base,
                                                                     :formula,
                                                                     :payment_day,
                                                                     :description,                                                                  
                                                                     :frequency,
                                                                     :slug,
                                                                     :category_number,
                                                                     :bind_withdraw
                                                                  ])
    end
end

app/helpers/debts_helper.rb
module DebtsHelper

    def status(status) 

        if status == "Amortização"
            return '<span class="badge badge-pill badge-warning">Amortização</span>'.html_safe 
        end
        if status == "Carência"
            return '<span class="badge badge-pill badge-info">Carência</span>'.html_safe 
        end
        if status == "Finalizado"
            return '<span class="badge badge-pill badge-success">Finalizado</span>'.html_safe 
        end

   

    end

end

app/views/debts/_form.html.erb
<%= simple_form_for(@debt, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-sm">
        <%= f.input :code, as: :string %>
      </div>
      <div class="col-sm">
        <%= f.input :name %>
      </div>
      <div class="col-sm">
        <%= f.input :signature_date, start_year: Date.today.year - 20, end_year: Date.today.year + 40 %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-sm">
        <%= f.association :creditor %>
      </div>
      <div class="col-sm">
        <%= f.input :category, as: :radio_buttons, collection: Debt.categories.keys, label_method: :titleize %>      
      </div>
      <div class="col-sm">
        <%= f.input :financial_agent_id, collection: Creditor.financial_agents %>
      </div>
    </div>  

    <br>

    <div class="row">
      <div class="col-sm">
        <%= f.input :contract_value %>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= f.association :currency %>
        </div>
        <div class="col-sm">
          <%= f.input :decimal_places %>
        </div>
      </div>      
    </div>

    <br>

    <div class="row">
      <div class="col-sm">
        <%= f.input :interest_rate %>
      </div>
      <div class="col-sm">
        <%= f.input :loan_term %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-sm">
        <%= f.input :grace_period, start_year: Date.today.year - 20, end_year: Date.today.year + 40 %>
        <%= f.input :start_amt_next_month_to_grace_period %>
      </div>
      <div class="col-sm">
        <%= f.input :amortization_period, start_year: Date.today.year - 20, end_year: Date.today.year + 40  %>
      </div>
      <div class="col-sm">
        <%= f.input :amortization_type, as: :radio_buttons, collection: Debt.amortization_types.keys, label_method: :titleize %>
      </div>      
    </div>

    <hr class="dashed-hr">
    
    <div class='links'>
      <h3>Movimentações
        <%= link_to_add_association fa_icon("plus-square", title: "Adicionar encargo"), f, :transaction_infos, 'data-association-insertion-method': :append, 'data-association-insertion-node': '#transaction_infos', class: 'add-charge text-primary' %>
      </h3>

    </div>

    <div id='transaction_infos'>    
      <%= f.simple_fields_for :transaction_infos do |transaction_info| %>       
        <%= render 'transaction_info_fields', f: transaction_info %>        
      <% end %>      
    </div>
    
    <hr class="dashed-hr">

    <br>

    <div class="row">
      <div class="col-sm">
        <%= f.input :applicable_legislation %>
      </div>
      <div class="col-sm">
        <%= f.input :legislation_level, as: :radio_buttons, collection: Debt.legislation_levels.keys, label_method: :titleize %>
      </div>
    </div>

    <%= f.input :purpose %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success pull-right" %>
  </div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="formula_modal" tabindex="-1" role="dialog" aria-labelledby="formulaModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Váriaveis de fórmula</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-stripped table-dark ">
          <thead>
            <tr>
              <th scope="col">Variável</th>
              <th scope="col">Função do sistema</th>
              <th scope="col">Descrição</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>[AMT]</code></td>
              <td>amortization</td>
              <td>Valor da próxima amortização</td>
            </tr>
            <tr>
              <td><code>[d]</code></td>
              <td>payment_day</td>
              <td>Dia do pagamento</td>
            </tr>
            <tr>
              <td><code>[DiNi]</code></td>
              <td>withdraws_pro_rata</td>
              <td>Lista de desembolsos multiplicado pelo período de referência</td>
            </tr>
            <tr>
              <td><code>[i]</code></td>
              <td>interest_rate</td>
              <td>Taxa de juros (%)</td>
            </tr>
            <tr>
              <td><code>[n]</code></td>
              <td>loan_term</td>
              <td>Número de parcelas</td>
            </tr>
            <tr>
              <td><code>[SD0]</code></td>
              <td>balance</td>
              <td>Valor do saldo inicial</td>
            </tr>
            <tr>
              <td><code>[SDf]</code></td>
              <td>outstanding_balance</td>
              <td>Valor do saldo final</td>
            </tr>
            <tr>
              <td><code>[VC]</code></td>
              <td>contract_value</td>
              <td>Valor total do contrato</td>
            </tr>
            
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#debt_category_interno').attr('checked', true);
  categoryInterno();
  
  $(".category").on('change', function(e) {    
    if ($(this).select('.category').val() == '1'){ 
      disableWithdrawInputs(this);
    } else {
      enableInputs(this);
    }
  });

  function disableWithdrawInputs(target){    
    $(target).parents('.nested-fields').find('.transaction-info-base').attr("disabled", true);
    $(target).parents('.nested-fields').find('.transaction-info-formula').attr("disabled", true);
    $(target).parents('.nested-fields').find('.transaction-info-payment-day').attr("disabled", true);
    $(target).parents('.nested-fields').find('.transaction-info-frequency').attr("disabled", true);
    $(target).parents('.nested-fields').find('.transaction-info-bind-withdraw').attr("disabled", true);
  };

  function enableInputs(target){
    $(target).parents('.nested-fields').find('*').removeAttr("disabled");
  }


  $('#debt_category_interno').on( "click", function() {
    categoryInterno();
  });

  $('#debt_category_externo').on( "click", function() {
    categoryExterno();
  });

  function categoryInterno(){
    $('#debt_financial_agent_id').val("");
    $('#debt_financial_agent_id').attr('disabled', true);
  }

  function categoryExterno(){
    $('#debt_financial_agent_id').attr('disabled', false);
  }  

</script>

app/views/debts/_transaction_info_fields.html.erb
<div class='nested-fields'>
	<div class="row">		
    <div class="col-sm-2 category-container">	
		  <%= f.input :category_number,collection: TransactionInfo::BASIC_TYPES.map {|k, v| [k, v[:name]] }, label_method: :last, value_method: :first, selected: f.object.category_number, input_html: { class: 'category' } %>
		</div>
		<div class="col-2">
			<%= f.input :base, input_html: { class: 'transaction-info-base' } %>
		</div>
   	<div class="col-sm">
			<%= f.input :formula, input_html: { class: 'transaction-info-formula' } %>
		</div>
		<div class="col-sm-1 formula-info">
		<!-- Button trigger modal -->
      <%= link_to fa_icon("question-circle 2x", title: "Ver variáveis de fórmula disponíveis"), '#', 'data-toggle': "modal", 'data-target': "#formula_modal", class: 'text-secondary' %>
    </div>
		
		<div class="col-1 trash-charge-container">
			<%= link_to_remove_association fa_icon("times-circle 2x", title: "Remover encargo") , f, class: 'text-danger' %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
		  <%= f.input :payment_day, input_html: { class: 'transaction-info-payment-day' } %>
		</div>
		<div class="col-sm-2">
			<%= f.input :frequency, as: :radio_buttons, collection: TransactionInfo.frequencies.keys, label_method: :titleize, input_html: { class: 'transaction-info-frequency' } %>
		</div>
		<div class="col-sm">
		  <%= f.input :description %>
		</div>
		<div class="col-1">
		  <% f.object.new_record? ? slug = f.object.category.slug : slug = f.object.slug %>
		  <%= f.input :slug, input_html: {value: slug} %>
		</div>
		<div class="col-sm-2"></div>
	</div>
		<div class="col-sm">
			<%= f.input :bind_withdraw, input_html: { class: 'transaction-info-bind-withdraw' }%>
		</div>

	<hr>
</div>

app/views/debts/edit.html.erb
<h1>Editar operação</h1>

<%= render 'form', debt: @debt %>

<%= link_to 'Show', @debt, class: 'btn' %> |
<%= link_to t('back'), debts_path, class: 'btn' %>

<script type="text/javascript">

  if ($("#debt_category_interno").prop("checked")) {
    categoryInterno();
  }else{
  	categoryExterno();
  }

</script>

app/views/debts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de operações</h1>
<hr>

<form class="form-inline my-2 my-lg-0" action="<%= search_debts_path %>" accept-charset="UTF-8" method="get">        
  
  <input class="form-control mr-sm-2" type="search" placeholder="Código" aria-label="Search" name="code_query" value="<%= params[:code_query] %>">
  <span class="mr-sm-2" >ou</span>
  <input class="form-control mr-sm-2" type="search" placeholder="Identificador" aria-label="Search" name="name_query" value="<%= params[:name_query] %>">
  <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="Ano da assinatura" aria-label="Search" name="signature_year_query" value="<%= params[:signature_year_query] %>">
  <%= select_tag "creditor_query", options_from_collection_for_select(Creditor.all, :id, :name, params[:creditor_query]), class: 'form-control select optional mr-sm-2 col-md-3', prompt: 'Selecionar credor' %>
  <%= select_tag "status_query", options_for_select(["Carência", "Amortização", "Finalizado"],
 params[:status_query]), class: 'form-control select optional mr-sm-2' , prompt: 'Selecionar status' %>
  <button class="btn btn-light my-2 my-sm-0" type="submit"><%= fa_icon("search", title: "Buscar") %></button>
</form>

<br>

<% if @debts.blank? %>

  <p class="text-center"><span class="mr-sm-2"><%= fa_icon("exclamation-triangle 2x") %></span>Não foram encontradas operações.</p>

<% else %>

  <table class='table table-striped table-hover'>
    <thead>
      <tr>
        <th>Código</th>
        <th>Identificador</th>
        <th>Data da assinatura</th>
        <th>Credor</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @debts.each do |debt| %>
        <tr>
          <td><%= debt.code %></td>
          <td><%= debt.name %></td>
          <td><%= debt.try(:signature_date).try(:strftime, "%d/%m/%Y") %></td>
          <td><%= debt.creditor.name %></td>
          <td><%= status(debt.status) %></td>
          <td><%= link_to fa_icon("eye 2x", title: "Mostrar"), debt, id: "mostra-#{debt.id}" %></td>
          <td><%= link_to fa_icon("edit 2x", title: "Editar"), edit_debt_path(debt) %></td>
          <td><%= link_to fa_icon("file 2x", title: "Relatório mensal"), month_report_path(debt_id: debt.id, :year => "", :month => ""), target: "_blank" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
 
  <div class="row">
  <div class="col sm  pull-left">
  <%== pagy_bootstrap_nav(@pagy) %>
  </div>
    <div class="col sm">
<%= link_to 'Cadastrar operação', new_debt_path, class: 'btn btn-success pull-right' %>
  </div>
  </div>
 
<br>

app/views/debts/new.html.erb
<h1>Cadastrar operação</h1>

<%= render 'form', debt: @debt %>

<%= link_to t('back'), debts_path, class: 'btn pull-right' %>

app/views/debts/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de operações</h1>
<hr>

<form class="form-inline my-2 my-lg-0" action="<%= search_debts_path %>" accept-charset="UTF-8" method="get">        
  
  <input class="form-control mr-sm-2" type="search" placeholder="Código" aria-label="Search" name="code_query" value="<%= params[:code_query] %>">
  <span class="mr-sm-2" >ou</span>
  <input class="form-control mr-sm-2" type="search" placeholder="Identificador" aria-label="Search" name="name_query" value="<%= params[:name_query] %>">
  <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="Ano da assinatura" aria-label="Search" name="signature_year_query" value="<%= params[:signature_year_query] %>">
  <%= select_tag "creditor_query", options_from_collection_for_select(Creditor.all, :id, :name, params[:creditor_query]), class: 'form-control select optional mr-sm-2 col-md-3', prompt: 'Selecionar credor' %>
  <%= select_tag "status_query", options_for_select(["Carência", "Amortização", "Finalizado"],
 params[:status_query]), class: 'form-control select optional mr-sm-2' , prompt: 'Selecionar status' %>
  <button class="btn btn-light my-2 my-sm-0" type="submit"><%= fa_icon("search", title: "Buscar") %></button>
</form>

<br>

<% if @debts.blank? %>

  <p class="text-center"><span class="mr-sm-2"><%= fa_icon("exclamation-triangle 2x") %></span>Não foram encontradas operações.</p>

<% else %>

  <table class='table table-striped table-hover'>
    <thead>
      <tr>
        <th>Código</th>
        <th>Identificador</th>
        <th>Data da assinatura</th>
        <th>Credor</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @debts.each do |debt| %>
        <tr>
          <td><%= debt.code %></td>
          <td><%= debt.name %></td>
          <td><%= debt.try(:signature_date).try(:strftime, "%d/%m/%Y") %></td>
          <td><%= debt.creditor.name %></td>
          <td><%= status(debt.status) %></td>
          <td><%= link_to fa_icon("eye 2x", title: "Mostrar"), debt, id: "mostra-#{debt.id}" %></td>
          <td><%= link_to fa_icon("edit 2x", title: "Editar"), edit_debt_path(debt) %></td>
          <td><%= link_to fa_icon("file 2x", title: "Relatório mensal"), month_report_path(debt_id: debt.id, :year => "", :month => ""), target: "_blank" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
 
  <div class="row">
  <div class="col sm  pull-left">
  
  </div>
    <div class="col sm">
<%= link_to 'Cadastrar operação', new_debt_path, class: 'btn btn-success pull-right' %>
  </div>
  </div>
 
<br>