config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  get 'reports/index', :to => 'reports#index', :as => 'reports'
  get '/month_report/', :to => 'month_reports#show', :as => 'month_report'
  get '/month_report/export', :to => 'month_reports#export', :as => 'export'
  get '/formulas/show/:formula', :to => 'formulas#show', :as => 'formula'

  # Api v1
  namespace :api do
    namespace :v1 do
     resources :currencies do 
      resources :manuals, only: %i[index create destroy]
     end
    end
  end

  resources :currencies
  resources :transaction_types
  resources :creditors
  
  resources :debts do
    resources :attachments
      collection do
        get 'search'
      end
    resources :transaction_items, :except => :show
  end
  
 
  root 'debts#index'
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  # mount_uploader :file, FileUploader
  
  has_one_attached :file

  belongs_to :debt

  validates :name, :presence => true
  validates :file, :presence => true
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  before_action :set_attachment, :only => [:show, :edit, :update, :destroy]
  before_action :set_debt, :only => [:index, :new, :create, :edit, :destroy, :update]
  before_action :set_attachments, :only => [:index, :create, :update, :destroy]
 # before_action :authenticate, only: [:crete, :update, :destroy, :show]
  
  # GET /attachments
  # GET /attachments.json
  def index   
    render :index, :layout => false
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show; end

  # GET /attachments/new
  def new
    @attachment = Attachment.new   
    render :new, :layout => false
  end

  # GET /attachments/1/edit
  def edit   
    render :edit, :layout => false
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)
   
    @attachment.debt = @debt
    
    respond_to do |format|
      if @attachment.save
        format.html { render :_index, :layout => false, :notice => 'O registro foi salvo com sucesso.' }
        format.json { render :show, :status => :created, :location => @attachment }
      else
        format.html { render :new }
        format.json { render :json => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { render :_index, :layout => false, :notice => 'O registro foi salvo com sucesso.' }
        format.json { render :show, :status => :ok, :location => @attachment }

      else
        format.html { render :edit }
        format.json { render :json => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    @attachment.file.purge
    respond_to do |format|
      format.html { render :_index, :layout => false, :notice => 'O registro foi removido com sucesso.' }
      format.json { head :no_content }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    def set_attachments
      @attachments = Attachment.all.where(:debt_id => @debt.id)
    end

    def set_debt
      @debt = Debt.find(params[:debt_id])
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == 'sadp' && password == Rails.application.credentials.storage_server_passwd
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :description, :file)
    end
end

app/views/attachments/_form.html.erb
<%=  simple_form_for [@debt, @attachment], url: [@debt, @attachment] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="modal-body">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
       
      <%= f.input :file, as: :file, direct_upload: true %>
    </div>
  </div>
<% end %>

app/views/attachments/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anexos</h1>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Arquivo</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.name %></td>
        <td><%= attachment.description %></td>
        <td>
          <%= link_to url_for(attachment.file), :target => "_blank" do %>
             <%= fa_icon('external-link', title: 'Abrir') %> Abrir
          <% end %>
        </td>
        <td>
         <a  data-toggle="modal" class="edit-attachment" data-target="#attachmentModal" href="<%= edit_debt_attachment_path(@debt, attachment) %>">
         <%= fa_icon('edit 2x') %>
         </a>
        </td>
        <td><%= link_to(fa_icon("trash 2x", title: "Remover"), [@debt, attachment], class: "remove-attachment", data: { confirm: 'Tem certeza?' } ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-success new-attachment pull-right" data-toggle="modal" data-target="#attachmentModal" data-path="<%= new_debt_attachment_path(@debt) %>">Novo anexo</button>

<div class="modal fade" id="attachmentModal" tabindex="-1" role="dialog" aria-labelledby="NovoAnexo" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">      
    </div>
  </div>
</div>

<script type="text/javascript">

  $('a.remove-attachment').on('click', function(e){
    e.preventDefault();
    $.ajax({ url: $(this).attr('href'), 
             method: 'DELETE'
      })
      .done(function(data) {
        console.log('AQUI');
          $('#nav-attachments').html(data);
              
      })
  })

  $('.edit-attachment').on('click', function(e){
    e.preventDefault();
    $.get($(this).attr('href'))
      .done(function( data ) {
        $('#attachmentModal .modal-content').html(data);
        initSubmitAttachment();
         
      });
    })

  $('.new-attachment').on('click', function (e) {
    $.get($(this).data('path'))
    .done(function( data ) {
      $('#attachmentModal .modal-content').html(data);
      initSubmitAttachment();
    });
  });

 function initSubmitAttachment(){

    $('button.attachment-save').on('click', function(e) {
      e.preventDefault();
     
      $.ajax({url: $(this).data('path'), 
              method: $(this).data('method'),
              data: new FormData($('form')[0]),
              contentType: false,
              processData: false
      })
      .done(function(data) {
        $('#attachmentModal').modal('hide');
        $('#attachmentModal').on('hidden.bs.modal', function (e) {
          $('#nav-attachments').html(data);
        })        
      })
      .fail(function(data) {
        $('#attachmentModal .modal-content').html(data.responseText);
        initSubmitAttachment();
      });
    });
  }

</script>

app/views/attachments/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Editar anexo</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', attachment: @attachment %>

<div class="modal-footer"> 
  <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
  <button type="button" data-path="<%= debt_attachment_path(@debt, @attachment) %>" data-method="PUT" class="btn btn-success attachment-save">Salvar</button>
</div>

app/views/attachments/new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Criar Anexo</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', attachment: @attachment %>

<div class="modal-footer"> 
  <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
  <button type="button" data-path="<%= debt_attachments_path(@debt) %>" data-method="POST" class="btn btn-success attachment-save">Salvar</button>
</div>