config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  get 'reports/index', :to => 'reports#index', :as => 'reports'
  get '/month_report/', :to => 'month_reports#show', :as => 'month_report'
  get '/month_report/export', :to => 'month_reports#export', :as => 'export'
  get '/formulas/show/:formula', :to => 'formulas#show', :as => 'formula'

  # Api v1
  namespace :api do
    namespace :v1 do
     resources :currencies do 
      resources :manuals, only: %i[index create destroy]
     end
    end
  end

  resources :currencies
  resources :transaction_types
  resources :creditors
  
  resources :debts do
    resources :attachments
      collection do
        get 'search'
      end
    resources :transaction_items, :except => :show
  end
  
 
  root 'debts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  <link rel="icon" type="image/png" href="<%= image_url('sigdiv.png') %>" />
    <title>SIGDIV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <!-- Style Sheet here -->
   <%= stylesheet_pack_tag 'application' %>
  <!-- Style Sheet here -->

    <%= stylesheet_link_tag 'application' %>
   <%= javascript_include_tag 'application'  %>
    <%= javascript_pack_tag 'application'  %>
  </head>

  <body data-flash-mensager="<%= JSON.dump(flash.to_a) %>">
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
      <div class="wide-container container">
        <a class="navbar-brand" href="<%= root_path %>"><%= image_tag asset_path("sigdiv.png"), class: "logo" %>SIGDIV</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link <%= controller_name == root_path ? "active" : "" %>" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
           
            <%= link_to 'Operações', debts_path, class: "nav-item nav-link #{controller_name == "debts" ? "active" : ""}" %>
            <%= link_to 'Credores', creditors_path, class: "nav-item nav-link #{controller_name == "creditors" ? "active" : ""}" %>
            <%= link_to 'Moedas', currencies_path, class: "nav-item nav-link #{controller_name == "currencies" ? "active" : ""}"  %>
            <%= link_to 'Relatórios', reports_path, class: "nav-item nav-link  #{controller_name == "reports" ? "active" : ""}" %>
            
          </div>
        </div>
      </div>
    </nav>

    <div class="wide-container container main-content">
      <%= yield %>
    </div>
   
     
  </body>
</html>